<?php
/**
 * AlipayOpenMiniInnerversionUploadstatusQueryResponseModel
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Alipay\OpenAPISDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * 支付宝开放平台API
 *
 * 支付宝开放平台v3协议文档
 *
 * The version of the OpenAPI document: 2023-08-31
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Alipay\OpenAPISDK\Model;

use \ArrayAccess;
use \Alipay\OpenAPISDK\ObjectSerializer;

/**
 * AlipayOpenMiniInnerversionUploadstatusQueryResponseModel Class Doc Comment
 *
 * @category Class
 * @package  Alipay\OpenAPISDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class AlipayOpenMiniInnerversionUploadstatusQueryResponseModel implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'AlipayOpenMiniInnerversionUploadstatusQueryResponseModel';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'buildInfo' => 'string',
        'buildPackageUrl' => 'string',
        'buildStatus' => 'string',
        'logUrl' => 'string',
        'needRotation' => 'string',
        'newBuildPackageUrl' => 'string',
        'newResultUrl' => 'string',
        'resultUrl' => 'string',
        'versionCreated' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'buildInfo' => null,
        'buildPackageUrl' => null,
        'buildStatus' => null,
        'logUrl' => null,
        'needRotation' => null,
        'newBuildPackageUrl' => null,
        'newResultUrl' => null,
        'resultUrl' => null,
        'versionCreated' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'buildInfo' => 'build_info',
        'buildPackageUrl' => 'build_package_url',
        'buildStatus' => 'build_status',
        'logUrl' => 'log_url',
        'needRotation' => 'need_rotation',
        'newBuildPackageUrl' => 'new_build_package_url',
        'newResultUrl' => 'new_result_url',
        'resultUrl' => 'result_url',
        'versionCreated' => 'version_created'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'buildInfo' => 'setBuildInfo',
        'buildPackageUrl' => 'setBuildPackageUrl',
        'buildStatus' => 'setBuildStatus',
        'logUrl' => 'setLogUrl',
        'needRotation' => 'setNeedRotation',
        'newBuildPackageUrl' => 'setNewBuildPackageUrl',
        'newResultUrl' => 'setNewResultUrl',
        'resultUrl' => 'setResultUrl',
        'versionCreated' => 'setVersionCreated'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'buildInfo' => 'getBuildInfo',
        'buildPackageUrl' => 'getBuildPackageUrl',
        'buildStatus' => 'getBuildStatus',
        'logUrl' => 'getLogUrl',
        'needRotation' => 'getNeedRotation',
        'newBuildPackageUrl' => 'getNewBuildPackageUrl',
        'newResultUrl' => 'getNewResultUrl',
        'resultUrl' => 'getResultUrl',
        'versionCreated' => 'getVersionCreated'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['buildInfo'] = $data['buildInfo'] ?? null;
        $this->container['buildPackageUrl'] = $data['buildPackageUrl'] ?? null;
        $this->container['buildStatus'] = $data['buildStatus'] ?? null;
        $this->container['logUrl'] = $data['logUrl'] ?? null;
        $this->container['needRotation'] = $data['needRotation'] ?? null;
        $this->container['newBuildPackageUrl'] = $data['newBuildPackageUrl'] ?? null;
        $this->container['newResultUrl'] = $data['newResultUrl'] ?? null;
        $this->container['resultUrl'] = $data['resultUrl'] ?? null;
        $this->container['versionCreated'] = $data['versionCreated'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets buildInfo
     *
     * @return string|null
     */
    public function getBuildInfo()
    {
        return $this->container['buildInfo'];
    }

    /**
     * Sets buildInfo
     *
     * @param string|null $buildInfo 构建信息
     *
     * @return self
     */
    public function setBuildInfo($buildInfo)
    {
        $this->container['buildInfo'] = $buildInfo;

        return $this;
    }

    /**
     * Gets buildPackageUrl
     *
     * @return string|null
     */
    public function getBuildPackageUrl()
    {
        return $this->container['buildPackageUrl'];
    }

    /**
     * Sets buildPackageUrl
     *
     * @param string|null $buildPackageUrl 构建好的包地址
     *
     * @return self
     */
    public function setBuildPackageUrl($buildPackageUrl)
    {
        $this->container['buildPackageUrl'] = $buildPackageUrl;

        return $this;
    }

    /**
     * Gets buildStatus
     *
     * @return string|null
     */
    public function getBuildStatus()
    {
        return $this->container['buildStatus'];
    }

    /**
     * Sets buildStatus
     *
     * @param string|null $buildStatus 构建状态
     *
     * @return self
     */
    public function setBuildStatus($buildStatus)
    {
        $this->container['buildStatus'] = $buildStatus;

        return $this;
    }

    /**
     * Gets logUrl
     *
     * @return string|null
     */
    public function getLogUrl()
    {
        return $this->container['logUrl'];
    }

    /**
     * Sets logUrl
     *
     * @param string|null $logUrl 构建日志地址
     *
     * @return self
     */
    public function setLogUrl($logUrl)
    {
        $this->container['logUrl'] = $logUrl;

        return $this;
    }

    /**
     * Gets needRotation
     *
     * @return string|null
     */
    public function getNeedRotation()
    {
        return $this->container['needRotation'];
    }

    /**
     * Sets needRotation
     *
     * @param string|null $needRotation 是否需要轮询
     *
     * @return self
     */
    public function setNeedRotation($needRotation)
    {
        $this->container['needRotation'] = $needRotation;

        return $this;
    }

    /**
     * Gets newBuildPackageUrl
     *
     * @return string|null
     */
    public function getNewBuildPackageUrl()
    {
        return $this->container['newBuildPackageUrl'];
    }

    /**
     * Sets newBuildPackageUrl
     *
     * @param string|null $newBuildPackageUrl 构建好的appx2.0包地址
     *
     * @return self
     */
    public function setNewBuildPackageUrl($newBuildPackageUrl)
    {
        $this->container['newBuildPackageUrl'] = $newBuildPackageUrl;

        return $this;
    }

    /**
     * Gets newResultUrl
     *
     * @return string|null
     */
    public function getNewResultUrl()
    {
        return $this->container['newResultUrl'];
    }

    /**
     * Sets newResultUrl
     *
     * @param string|null $newResultUrl 构建的结果地址
     *
     * @return self
     */
    public function setNewResultUrl($newResultUrl)
    {
        $this->container['newResultUrl'] = $newResultUrl;

        return $this;
    }

    /**
     * Gets resultUrl
     *
     * @return string|null
     */
    public function getResultUrl()
    {
        return $this->container['resultUrl'];
    }

    /**
     * Sets resultUrl
     *
     * @param string|null $resultUrl 构建的结果地址
     *
     * @return self
     */
    public function setResultUrl($resultUrl)
    {
        $this->container['resultUrl'] = $resultUrl;

        return $this;
    }

    /**
     * Gets versionCreated
     *
     * @return string|null
     */
    public function getVersionCreated()
    {
        return $this->container['versionCreated'];
    }

    /**
     * Sets versionCreated
     *
     * @param string|null $versionCreated 创建版本结果
     *
     * @return self
     */
    public function setVersionCreated($versionCreated)
    {
        $this->container['versionCreated'] = $versionCreated;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


